source 'https://rubygems.org'

ruby '3.0.0'

gem 'rails', '~> 7.0.4'
gem 'puma', '~> 5.6'
gem 'pg', '>= 1.1', '< 2.0'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'pry-byebug'
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.3'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'factory_bot_rails'
end